### ISSUE TITLE
Wish list for Spring 2020 semester in FOSS

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#105]
# Summary

Collect a wish list of ideas and projects for things next semester

# Background

In FOSS Hours on Dec. 5th, 2019, we brainstormed a bit of some things people would like to see from the FOSS@MAGIC program. We cannot commit to everything, but it helps for us to understand what folks would like to see from us.

# Details

- [ ] Bridge a single `#foss` channel across different RIT sub-communities
- [X] ~~Collaborate with RGDC to talk Linux, gaming, and (cross-platform) game dev~~ #106
- [X] ~~@WillNilges: Resolving innate paradox in the statement "FOSS gaming"~~ #106
- [ ] @WillNilges: CSH + RITlug/FOSS collaboration
- [X] ~~Documenting FOSS@RIT community and infrastructure~~ #107

# Outcome

Start piecing together a roadmap for outreach / events we want to do in Spring 2020

**Comment by ct-martin** [comment]
I would like to see a smaller "bus factor" across FOSS projects/infrastructure. We have a lot of cool initiatives and unfortunately some have only one person who has admin access to them from my knowledge. While technically keys to some of these things have been rumored to be in safe places, there are not necessarily more than one person who knows how to use them. Additionally, some of these things seem to have opinionated configurations and I am not aware of any documentation on some of them. We've had times where we needed to call people at events to get last-minute things done and I'd like to be able to avoid this in the future (particularly since concerns have come up about others that haven't been an issue yet).

Some examples:
* `foss_bot` (this matters less now but would matter more if we add Q&A to it)
* Discourse
* IRC cloaks/masks (mainly documentation)
* IRC bridges
* GitHub Org (this one I think might have enough people)
  * Website (we do have a good number of people for this but more helps when changes needed on short notice)
* FOSS letters (specifically `fl3`)

Again, this is not to say that nothing exists already; there is some basic documentation around (and I know that `foss_bot` is more of a @ritjoe project than a FOSS@MAGIC project per say). However, there's a lot more that can be done. Here are the specific items that I would like to see:
* More people who have access to infra
  * Both have technical access and know how to fix things
  * 3 would be a good safe number (for example)
* API accounts used by infra not tied to personal accounts
* Documentation
  * Name
  * Links to important documentation
  * How to run
  * Updating
  * Configuration quirks (e.g. notable changes from a default config)
  * Admin contacts
    * If physical parts, who has them
    * Who has admin access to interface (as in Freenode channel ops)
    * Who has admin access to host (as in sudo access to VM)
    * Other contacts (e.g. IRC-lug is hosted by RITlug and RITlug could turn it off if needed)

This would also be good to consider as part of #103. For the short term, it's be best to at least have a complete list of who has access to what infra/projects.

**Comment by jwflory** [comment]
@ct-martin I hear your feedback and admittedly I know a lot of your feedback is looking at me. :slightly_smiling_face: I'm going to work on addressing most of this in #107. Some of it is already addressed, but it is only visible to MAGIC payroll staff (e.g. API accounts owned by an account managed by Brenda or shared account credentials among a group of folks).

Also, I'm throwing my own coin in the Spring 2020 wishing well: I'd like for us to move towards defining a mentorship structure, particularly from upperclassfolks to lowerclassfolks, to help address the sustainability of student participation in FOSS@RIT community initiatives (I _am_ distinguishing FOSS@RIT from FOSS@MAGIC in this case.)

**Comment by ct-martin** [comment]
@jwflory I was trying to avoid singling you out, but yes, some things are pointed at you. In particular, I have concern with the official/visible email on the GitHub Org pointing to your personal domain.

However, I would also like to make clear that this is not focused on you specifically, and also not limited to documentation. This also applies to projects we run that get demo-ed at events, for example FOSS Letters, and access to things, for example, you trying to move `foss_bot` this morning or last minute PRs for FIO.

I think #107 is a good first step, and I think that there is more to be done on top of that. With regards to accounts kept to FOSS@MAGIC payroll staff, I should make clear that my intent was public documentation that they exist and who to contact for them, but we don't need every detail about them; the point is mainly that we have an inventory of what we have and contacts if something breaks. Having clear documentation that says "we have this but you should absolutely not be messing with it" is acceptable to this end (albeit not in that time of voice).

I think it may be worthwhile to get a `foss@rit.edu` (or `foss@magic.rit.edu`) forwarding email that goes to payroll staff and can be the official contact for accounts (unless billing requires otherwise) as well as general inquiries. This would provide a default that isn't a personal account for FOSS@MAGIC things. If there are questions on how to get an `@rit.edu` email, we could ask one of the helpful ITS contacts we have in some of the RITlug channels.

I also think a new issue should be opened to discuss mentoring (also semi-related to #103 ). I am currently travelling so if I don't get a chance to open it soon, please feel free to open one yourself. This is likely a conversation that will need to happen in-person, having an issue to track would still be worthwhile though.

**Comment by itprofjacobs** [comment]
Glad to discuss all of this.

Re billing, finances, etc, since this isn’t a club any requests for $ have to be emailed to me so that I can reply with a CC to Brenda who then process the financial stuff.  Some of the stuff in JFlory’s name is historical due to transitions between MAGIC leadership etc, and will all be converted over the next few months.

**Comment by jwflory** [comment]
> I think it may be worthwhile to get a `foss [at] rit [dot] edu` (or `foss [dot] magic [dot] rit [dot] edu`) forwarding email that goes to payroll staff and can be the official contact for accounts (unless billing requires otherwise) as well as general inquiries. This would provide a default that isn't a personal account for FOSS@MAGIC things. If there are questions on how to get an `@rit.edu` email, we could ask one of the helpful ITS contacts we have in some of the RITlug channels.

To make note of this, I worked with Chris Helming at ITS today to get `foss [at] rit [dot] edu` created. It goes to me, @itprofjacobs, and Brenda. The GitHub organization is updated to use this email and I will continue to update other shared accounts to use this forwarding alias too.

**Comment by jwflory** [comment]
Okay, I think this issue led to good discussion and planning for focuses this semester, with the limited bandwidth we have. The Tech Team has its first meeting this Sunday, @whenbellstoll has the FOSS outreach for RGDC on his radar (#106), I am documenting a lot of knowledge in my head into the public (#107), and we are also working on financial sustainability concerns (#110).

I'm closing this issue. We can drive more specific conversation in the existing issues or in new issues. :ocean:
