### ISSUE TITLE
Add historical community projects to FOSS@MAGIC website

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#113]
# Summary

Add historical projects associated to the FOSS@RIT / FOSS@MAGIC community to the FOSS@MAGIC website on GitHub Pages

# Background

In a phone conversation with @itprofjacobs, I mentioned the historical archive of projects I found buried on the MAGIC Center's old website. It's unclear where this content will go in a month, yet alone a year. So instead of letting it remain buried on the Internet, it would be nice to bring them onto the _Projects_ section of our website and give publicity to past student and faculty efforts done over the years.

# Details

Should be completed by Thursday evening, March 5th, before the RIT open source faculty meeting.

Current list of historical projects:

- [x] ~~[AngleGators](https://magic.rit.edu/anglegators/)~~ FOSSRIT/fossrit.github.io#103
- [x] ~~[ZeroQuest](https://magic.rit.edu/zeroquest/)~~ FOSSRIT/fossrit.github.io#104
- [x] ~~[LZR](https://magic.rit.edu/lzr/)~~ FOSSRIT/fossrit.github.io#105
- [x] ~~[LearnIt](https://magic.rit.edu/learnit/)~~ FOSSRIT/fossrit.github.io#106
- [x] ~~[PyCut](https://magic.rit.edu/pycut/)~~ FOSSRIT/fossrit.github.io#107
- [x] ~~[SkyTime](https://web.archive.org/web/20160509042320/https://magic.rit.edu/?page_id=1008)~~ FOSSRIT/fossrit.github.io#109
- [x] ~~[Fractionauts](https://web.archive.org/web/20160509042320/https://magic.rit.edu/?page_id=1008)~~ FOSSRIT/fossrit.github.io#108
- [x] ~~[Lemonade Stand](https://web.archive.org/web/20160509042320/https://magic.rit.edu/?page_id=1008)~~ FOSSRIT/fossrit.github.io#131
- [x] ~~[Fortune Hunter](https://web.archive.org/web/20160509042320/https://magic.rit.edu/?page_id=1008)~~ FOSSRIT/fossrit.github.io#130
- [x] ~~[Open Video Chat](https://web.archive.org/web/20160509042320/https://magic.rit.edu/?page_id=1008)~~ FOSSRIT/fossrit.github.io#132
- [x] ~~[Blocku](https://web.archive.org/web/20160509042320/https://magic.rit.edu/?page_id=1008)~~ FOSSRIT/fossrit.github.io#133
- [x] ~~[CIVX](https://web.archive.org/web/20160509042320/https://magic.rit.edu/?page_id=1008)~~ FOSSRIT/fossrit.github.io#134

# Outcome

Better representation of the past ten years of FOSS projects at RIT on our website

**Comment by ritjoe** [comment]
On Fri, Feb 28, 2020 at 10:38:43AM -0800, jwflory wrote:
>   • [ ] Fractionauts

http://wiki.sugarlabs.org/go/Fractionauts

which includes links

http://activities.sugarlabs.org/en-US/sugar/addon/4746/

https://github.com/chrisknepper/Fractionauts

there are 6 forks of Fractionauts, amongst which include

https://github.com/FOSSRIT/Fractionauts

but also a few that are, for instance, not obviously FOSS@RIT related
